#!/bin/bash

while IFS= read -r line; do
    PACKAGE=$(echo "$line" | cut -d ' ' -f1)
    VERSION=$(echo "$line" | cut -d ' ' -f2)
    
    echo "${VERSION}" > "${PACKAGE}"
done < ../dir

echo "cbon."
