#!/bin/bash

# Définir les variables
MIRROR_URL="https://mirror.thekinrar.fr/archlinux/"
CORE_BRANCH="core"
COMMUNITY_BRANCH="community"
CACHE_FILE="/etc/cydramanager/cache"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Fonction d'aide
function show_help {
    echo "Cydramanager - Gestionnaire de paquets simple pour Arch Linux"
    echo ""
    echo "Utilisation: cydramanager [install/remove] [nom_du_paquet]"
    echo ""
    echo "Options:"
    echo "  install              Installe le paquet spécifié"
    echo "  remove               Supprime le paquet spécifié"
    echo "  help                 Affiche ce message d'aide"
}

# Vérifier si l'utilisateur est root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Ce script doit être exécuté avec les privilèges root${NC}" 
   exit 1
fi

# Vérifier que les arguments sont fournis
if [[ $# -eq 0 ]]; then
    show_help
    exit 0
elif [[ $# -ne 2 ]]; then
    echo -e "${RED}Deux arguments sont nécessaires (install/remove) et le nom du paquet${NC}"
    exit 1
fi

# Vérifier que l'argument d'action est valide
if [[ "$1" != "install" && "$1" != "remove" ]]; then
    echo -e "${RED}L'action doit être install ou remove${NC}"
    exit 1
fi

PACKAGE="$2"
# Installer le paquet
if [[ "$1" == "install" ]]; then
    mkdir ${CACHE_FILE}
    wget ${MIRROR_URL}/${COMMUNITY_BRANCH}/community.db.tar.gz -P ${CACHE_FILE}
    wget ${MIRROR_URL}/${CORE_BRANCH}/core.db.tar.gz -P ${CACHE_FILE}/
    tar xf ${CACHE_FILE}/core.db.tar.gz -C ${CACHE_FILE} > /dev/null 2>&1;
    tar xf ${CACHE_FILE}/community.db.tar.gz -C ${CACHE_FILE} > /dev/null 2>&1;
    PKG_INFO=$(grep -r -l $PACKAGE"-" /etc/cydramanager/cache)
    PKG_VERSION=$(sed -n 11p ${PKG_INFO})
    PKG_ARCHIVE=$(awk '/%FILENAME%/ {flag=1; next} flag {print; flag=0}' exemple.txt)
    DEPENDS_LIST=${awk '/%DEPENDS%/ {flag=1; next} flag && !/^$/ {print} !flag && /^$/ {exit}' $PKG_INFO}

    echo -e "${GREEN}Les paquets sont mis a jour${NC}"
    wget ${MIRROR_URL}/${COMMUNITY_BRANCH}/${PKG_ARCHIVE}
    wget ${MIRROR_URL}/${CORE_BRANCH}/${PKG_ARCHIVE}
    tar xf ${PACKAGE}"-"${PKG_VERSION}"-x86_64.pkg.tar.zst" -C /
    echo -e "${GREEN}Installation des dépendances..${NC}"
    echo -e "${GREEN}Le paquet $PACKAGE a été installé avec succès${NC}"
    rm -f ${CACHE_FILE}
elif [[ "$1" == "remove" ]]; then
    echo -e "${GREEN}Suppression du paquet $PACKAGE${NC}"
    if ! command -v "$PACKAGE" >/dev/null 2>&1; then
        echo -e "${RED}Le paquet $PACKAGE n'est pas installé${NC}"
        exit 1
    fi
    PKG_FILES=$(find / -name "*${PACKAGE}*")
    for FILE in $PKG_FILES; do
        if [ -f "$FILE" ]; then
            rm "$FILE"
        elif [ -d "$FILE" ]; then
            rm -r "$FILE"
        fi
    done
    echo -e "${GREEN}Le paquet $PACKAGE a été supprimé avec succès${NC}"
fi

exit 0
