#!/bin/bash

# Définir les variables
MIRROR_URL="https://mirror.thekinrar.fr/archlinux/"
CORE_BRANCH="core"
COMMUNITY_BRANCH="community"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Fonction d'aide
function show_help {
    echo "Cydramanager - Gestionnaire de paquets simple pour Arch Linux"
    echo ""
    echo "Utilisation: cydramanager [install/remove] [nom_du_paquet]"
    echo ""
    echo "Options:"
    echo "  install              Installe le paquet spécifié"
    echo "  remove               Supprime le paquet spécifié"
    echo "  help                 Affiche ce message d'aide"
}

# Vérifier si l'utilisateur est root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Ce script doit être exécuté avec les privilèges root${NC}" 
   exit 1
fi

# Vérifier que les arguments sont fournis
if [[ $# -eq 0 ]]; then
    show_help
    exit 0
elif [[ $# -ne 2 ]]; then
    echo -e "${RED}Deux arguments sont nécessaires (install/remove) et le nom du paquet${NC}"
    exit 1
fi

# Vérifier que l'argument d'action est valide
if [[ "$1" != "install" && "$1" != "remove" ]]; then
    echo -e "${RED}L'action doit être install ou remove${NC}"
    exit 1
fi

# Vérifier que le paquet existe
PACKAGE="$2"
PACKAGE_URL="${MIRROR_URL}/${CORE_BRANCH}/${PACKAGE}"
if ! wget --spider "$PACKAGE_URL" >/dev/null 2>&1; then
    PACKAGE_URL="${MIRROR_URL}/${COMMUNITY_BRANCH}/${PACKAGE}"
    if ! wget --spider "$PACKAGE_URL" >/dev/null 2>&1; then
        echo -e "${RED}Le paquet $PACKAGE n'a pas été trouvé${NC}"
        exit 1
    fi
fi

# Installer le paquet
if [[ "$1" == "install" ]]; then
    echo -e "${GREEN}Installation du paquet $PACKAGE${NC}"
    wget "$PACKAGE_URL"
    tar xf "${PACKAGE}-*.tar.xz"
    cd "${PACKAGE}"
    makepkg -si
    cd ..
    rm -rf "${PACKAGE}" "${PACKAGE}-*.tar.xz"
    echo -e "${GREEN}Le paquet $PACKAGE a été installé avec succès${NC}"

# Supprimer le paquet
elif [[ "$1" == "remove" ]]; then
    echo -e "${GREEN}Suppression du paquet $PACKAGE${NC}"
    if ! command -v "$PACKAGE" >/dev/null 2>&1; then
        echo -e "${RED}Le paquet $PACKAGE n'est pas installé${NC}"
        exit 1
    fi
    PKG_FILES=$(find / -name "*${PACKAGE}*")
    for FILE in $PKG_FILES; do
        if [ -f "$FILE" ]; then
            rm "$FILE"
        elif [ -d "$FILE" ]; then
            rm -r "$FILE"
        fi
    done
    echo -e "${GREEN}Le paquet $PACKAGE a été supprimé avec succès${NC}"
fi

exit 0
